### ISSUE TITLE
Obsolete dependencies

### ISSUE THREAD

**Issue by flaringapp** [wzieba/Firebase-Distribution-Github-Action#50] opened 2021-10-31 19:24 UTC
This action currently uses some obsolete dependencies according to workflow logs. Please consider updating those.
Logs:

```
warning firebase-tools > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

warning firebase-tools > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

warning firebase-tools > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

warning firebase-tools > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

warning firebase-tools > universal-analytics > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

warning firebase-tools > request > har-validator@5.1.5: this library is no longer supported
```

**Comment by mateuszkwiecinski** [comment] 2021-11-01 20:06
Duplicate of https://github.com/wzieba/Firebase-Distribution-Github-Action/issues/27

This Action uses latest `firebase-tools` version (btw. shouldn't the installed version be customizable for security reasons?) which depends on deprecated dependencies. The issue has been reported to Firebase team and can be tracked in dedicated issue: https://github.com/firebase/firebase-tools/issues/2215

**Closed** 2021-12-06 18:20 UTC
